name: Greet User
on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello, World!"
      - name: Introduction
        run: echo "This is a simple GitHub Actions workflow."